server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://rm-2ze94o96k445m1c4tqo.mysql.rds.aliyuncs.com:3306/ssq
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
knife4j:
  enable: true

url:
  cwl:
    domain: https://www.cwl.gov.cn
    ssq: /cwl_admin/front/cwlkj/search/kjxx/findDrawNotice?name=ssq&issueCount=&issueStart=&issueEnd=&dayStart=&dayEnd=&pageNo=1&pageSize=20&week=&systemType=PC

ssq:
  url: https://www.cwl.gov.cn/cwl_admin/front/cwlkj/search/kjxx/findDrawNotice?name=ssq&issueCount=&issueStart=&issueEnd=&dayStart=&dayEnd=&pageNo=1&pageSize=50&week=&systemType=PC
mybatis:
  configuration:
    map-underscore-to-camel-case: true